sca_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: square # Snowflake <account_name>
      user: ronnieg@squareup.com # Snowflake username
      role: ronnieg # Snowflake user role

      # SSO config
      authenticator: externalbrowser

      database: personal_ronnieg # Snowflake database name
      warehouse: ADHOC_LARGE # Snowflake warehouse name
      schema: dbt_staging
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt_test

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false