version: 2

sources:
  - name: merchantcomphub
    database: merchantcomp_hub
    schema: raw_oltp
    tables:
      - name: qc_decision
	  - name: qc_dispute
	  - name: qc_question_answer
	  - name: qc_decision_followup